### ISSUE TITLE
Google search for pagerjs points at 404 pages

### ISSUE THREAD

**Issue by slisznia** [finnsson/pagerjs#181]
It's been like this for months:
http://pagerjs.com/demo/#!/modals

Instead of:
http://pagerjs.com/demo/#!/view/modals

Query:
https://www.google.com/search?q=pagerjs+modal

**Comment by quickstep25** [comment]
I get the same results when I use your google search query above; why is this important?  Are you using this as example because you are experiencing flawed reference links for your personal application when Google crawls your site?

Otherwise, just doing a search for 'pagerjs' in google brings up correct link as such:

![image](https://cloud.githubusercontent.com/assets/3681250/5791237/41664e40-9e95-11e4-9c41-45780727bc7f.png)

**Comment by finnsson** [comment]
I'll make a new attempt at solving this by deleting old snapshots on the server.
